import React, { createContext, useContext, useState, ReactNode } from 'react';

export type Language = 'it' | 'en';

interface LanguageContextType {
  language: Language;
  setLanguage: (language: Language) => void;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};

interface LanguageProviderProps {
  children: ReactNode;
}

const translations = {
  it: {
    // Navigation
    'nav.representatives': 'Rappresentanti',
    'nav.handouts': 'Dispense',
    'nav.exchange': 'Exchange',
    'nav.directory': 'Directory',
    'nav.guides': 'Guide',
    'nav.about': 'Chi Siamo',
    'nav.calculators': 'Calcolatori',
    
    // Hero Section
    'hero.subtitle': 'La tua associazione studentesca di riferimento in Bocconi. Scopri tutti i servizi e le opportunità che mettiamo a disposizione per rendere la tua esperienza universitaria indimenticabile.',
    'hero.aboutUs': 'Chi Siamo',
    'hero.contact': 'Contattaci',
    'board.title': 'Our Board',
    
    // About Section
    'about.title': 'Chi Siamo',
    'about.subtitle': 'ASTRA è l\'associazione studentesca che rappresenta gli studenti della Bocconi, offrendo servizi, supporto e opportunità per migliorare l\'esperienza universitaria di tutti.',
    'about.innovation.title': 'Innovazione',
    'about.innovation.description': 'Promuoviamo soluzioni innovative per migliorare l\'esperienza universitaria attraverso tecnologia e creatività.',
    'about.community.title': 'Community',
    'about.community.description': 'Costruiamo una community forte e collaborativa che supporta ogni studente nel raggiungimento dei propri obiettivi.',
    'about.future.title': 'Futuro',
    'about.future.description': 'Prepariamo gli studenti per il futuro professionale con opportunità concrete e orientamento personalizzato.',
    
    // Values Section
    'values.title': 'I Nostri Valori',
    'values.subtitle': 'I principi che guidano ogni nostra azione e decisione',
    'values.ambition.title': 'Ambizione',
    'values.ambition.description': 'Non è arrivismo, ma volontà di spingersi oltre. Guardare avanti, cercare soluzioni migliori e non fermarsi mai.',
    'values.communication.title': 'Comunicazione',
    'values.communication.description': 'Le idee valgono solo se vengono ascoltate. Il dialogo tra studenti e Università è la chiave per costruire un vero cambiamento.',
    'values.dedication.title': 'Dedizione',
    'values.dedication.description': 'Nulla si ottiene senza costanza e impegno. Solo chi si mette in gioco ogni giorno può lasciare il segno.',
    
    // What We Do Section
    'whatwedo.title': 'Cosa Facciamo',
    'whatwedo.subtitle': 'La nostra visione della rappresentanza si sviluppa attraverso tre aspetti fondamentali dell\'esperienza universitaria',
    'whatwedo.handouts.title': 'Dispense e Materiali',
    'whatwedo.handouts.description': 'Accesso facilitato a dispense, appunti e materiali di studio per tutti i corsi',
    'whatwedo.exchange.title': 'Exchange Program',
    'whatwedo.exchange.description': 'Supporto completo per programmi di scambio internazionale e opportunità all\'estero',
    'whatwedo.representation.title': 'Rappresentanza Attiva',
    'whatwedo.representation.description': 'La tua voce negli organi universitari per migliorare l\'esperienza di tutti',
    'whatwedo.innovation.title': 'Innovazione Didattica',
    'whatwedo.innovation.description': 'Promuoviamo nuovi metodi di apprendimento e tecnologie per la formazione',
    'whatwedo.career.title': 'Orientamento Carriera',
    'whatwedo.career.description': 'Guide e supporto per costruire il tuo percorso professionale',
    'whatwedo.wellbeing.title': 'Benessere Studenti',
    'whatwedo.wellbeing.description': 'Iniziative per il benessere psicofisico e l\'equilibrio studio-vita',
    'whatwedo.approach.title': 'Un approccio a 360° per la tua esperienza universitaria',
    'whatwedo.approach.description': 'Non ci limitiamo alla rappresentanza tradizionale. Creiamo un ecosistema di supporto che accompagna ogni studente dal primo giorno fino alla laurea, costruendo una community forte e collaborativa.',
    
    // Team Section
    'team.title': 'Il Nostro Team',
    'team.subtitle': 'Conosci i rappresentanti che lavorano per migliorare la tua esperienza universitaria. Un team diversificato con competenze complementari.',
    'team.search': 'Cerca per nome, ruolo o corso...',
    'team.all': 'tutti',
    'team.presidency': 'Presidenza',
    'team.senate': 'Senato Accademico',
    'team.events': 'Eventi',
    'team.innovation': 'Innovazione',
    'team.communication': 'Comunicazione',
    'team.exchange': 'Exchange',
    'team.welfare': 'Welfare',
    'team.no-results': 'Nessun membro trovato con i filtri attuali.',
    'team.stats.representatives': 'Rappresentanti Attivi',
    'team.stats.bodies': 'Organi Rappresentati',
    'team.stats.courses': 'Corsi di Laurea',
    'team.stats.students': 'Studenti Rappresentati',
    
    // Representatives Section
    'representatives.title': '🏛️ I Nostri Rappresentanti',
    'representatives.subtitle': 'Scopri le diverse aree di rappresentanza studentesca. I nostri rappresentanti lavorano in vari organi e commissioni per tutelare i tuoi diritti e migliorare la vita universitaria.',
    'representatives.loading': 'Caricamento rappresentanti...',
    'representatives.viewReps': 'Vedi Rappresentanti',
    'representatives.hide': 'Nascondi',
    'representatives.learnMore': 'Scopri di più',
    'representatives.count': 'rappresentant',
    'representatives.countSingle': 'e',
    'representatives.countPlural': 'i',
    'representatives.noReps': 'Nessun rappresentante attualmente disponibile per questa sezione.',
    'representatives.cdd.description': 'Commissione di Disciplina Didattica - Gestione delle questioni disciplinari e didattiche',
    'representatives.dipartimenti.description': 'Rappresentanza nei diversi dipartimenti accademici dell\'università',
    'representatives.isu.description': 'Istituto per il Sostegno Universitario - Servizi per il diritto allo studio',
    'representatives.qualita.description': 'Commissione per la Qualità - Monitoraggio e miglioramento della qualità didattica',
    'representatives.giurisprudenza.description': 'Rappresentanza nella Scuola di Giurisprudenza',
    'representatives.magistrale.description': 'Rappresentanza nelle scuole magistrali e corsi di laurea magistrale',
    'representatives.triennale.description': 'Rappresentanza nelle scuole triennali e corsi di laurea triennale',
    'representatives.sport.description': 'Rappresentanza nelle attività sportive e ricreative universitarie',
    'representatives.valutazione.description': 'Commissione di Valutazione - Valutazione delle performance accademiche',
    
    // Handouts Section
    'handouts.title': 'Dispense e Guide',
    'handouts.subtitle': 'Accedi alle risorse di studio condivise dalla community. Trova dispense, riassunti e guide per ogni corso.',
    'handouts.search': 'Cerca per materia o nome file...',
    'handouts.firstYear': '1° Anno',
    'handouts.secondYear': '2° Anno',
    'handouts.thirdYear': '3° Anno',
    'handouts.loading': 'Caricamento dispense...',
    'handouts.uploaded': 'Caricato:',
    'handouts.download': 'Scarica PDF',
    'handouts.seeAll': 'Vedi tutte le dispense del',
    'handouts.seeAllGeneral': 'Vedi tutte le dispense',
    'handouts.results': 'risultat',
    'handouts.resultsFound': 'trovato per',
    'handouts.noResults': 'Nessuna dispensa',
    'handouts.noResultsSearch': 'trovata per',
    'handouts.noResultsYear': 'disponibile per',
    
    // Astra Polare Section
    'astrapolare.title': 'Astra Polare',
    'astrapolare.subtitle': 'Il nostro magazine digitale. Contenuti, storie e media che raccontano la vita universitaria dal punto di vista degli studenti.',
    'astrapolare.recent': 'Più Recenti',
    'astrapolare.popular': 'Più Visti',
    'astrapolare.trending': 'Trending',
    'astrapolare.loading': 'Caricamento contenuti...',
    'astrapolare.error': 'Errore nel caricamento dei contenuti',
    'astrapolare.retry': 'Riprova',
    'astrapolare.noContent': 'Nessun contenuto disponibile al momento.',
    'astrapolare.slides': 'slides',
    'astrapolare.views': 'views',
    'astrapolare.visualizations': 'visualizzazioni',
    'astrapolare.followSocial': 'Seguici sui Social',
    'astrapolare.followDescription': 'Non perdere i nostri contenuti! Seguici su TikTok e Instagram per restare aggiornato.',
    'astrapolare.tiktok': '📱 TikTok',
    'astrapolare.instagram': '📸 Instagram',
    
    // Astra GPT Section
    'astragpt.title': 'Astra GPT',
    'astragpt.powered': 'Powered by AI',
    'astragpt.subtitle': 'Il tuo assistente virtuale intelligente per navigare la vita universitaria Bocconi. Sempre disponibile, sempre aggiornato.',
    'astragpt.description': 'Scopri il nuovo AstraGPT 2.0 - potenziato con l\'intelligenza artificiale più avanzata per supportarti nella tua vita universitaria Bocconi.',
    'astragpt.try': 'Prova Astra GPT 2.0!',
    'astragpt.open': 'Apri AstraGPT 2.0',
    
    // Calculators Section
    'calculators.title': 'Calcolatori Smart',
    'calculators.subtitle': 'Tool intelligenti per ottimizzare il tuo percorso universitario. Pianifica, calcola e raggiungi i tuoi obiettivi accademici.',
    'calculators.gpa.title': 'GPA & Graduation Score (Triennale)',
    'calculators.gpa.description': 'Calcola il tuo voto di laurea previsto basato sui tuoi esami',
    'calculators.gpa-msc.title': 'GPA & Graduation Score (Magistrale)',
    'calculators.gpa-msc.description': 'Calcola il voto di laurea magistrale con tesi e bonus',
    'calculators.exchange-msc.title': 'Exchange Calculator MSc',
    'calculators.exchange-msc.description': 'Calcola il tuo Exchange Score e scopri le destinazioni disponibili',
    'calculators.exchange-clmg.title': 'Exchange Calculator CLMG',
    'calculators.exchange-clmg.description': 'Calcola il tuo punteggio per l\'exchange in Giurisprudenza',
    'calculators.exchange-ug.title': 'Exchange Calculator UG',
    'calculators.exchange-ug.description': 'Calcola il tuo Exchange Score per l\'Undergraduate e scopri le destinazioni disponibili',
    'calculators.features': 'Funzionalità:',
    'calculators.use': 'Usa Calcolatore',
    'calculators.feat.gpa.1': 'Voto di laurea su 110',
    'calculators.feat.gpa.2': 'GPA su 30',
    'calculators.feat.gpa.3': 'Bonus configurabili',
    'calculators.feat.exchange.1': 'Calcolo Exchange Score',
    'calculators.feat.exchange.2': 'Destinazioni per continente',
    'calculators.feat.exchange.3': 'Acceptance Rate',
    
    // MSc Calculator
    'msc_calc.select_course': 'Seleziona Corso di Laurea Magistrale',
    'msc_calc.select_course_placeholder': 'Scegli il tuo corso di laurea magistrale',
    'msc_calc.select_track': 'Seleziona Track',
    'msc_calc.select_track_placeholder': 'Scegli il tuo track',
    'msc_calc.gpa_tooltip': 'Media ponderata dei voti per i crediti. "30 e lode" = 30 nel calcolo.',
    'msc_calc.base_score': 'Punteggio Base',
    'msc_calc.base_score_tooltip': 'Conversione in centodecimi: (GPA / 30) × 110',
    'msc_calc.graduation_grade': 'Voto di Laurea',
    'msc_calc.graduation_tooltip': 'Punteggio base + punti tesi + bonus. Se ≥ 110 → Eligible for 110 e Lode.',
    'msc_calc.out_of_30': 'su 30',
    'msc_calc.out_of_110': 'su 110',
    'msc_calc.lode_badge': 'Eligible for 110 e Lode (soggetto ad approvazione della commissione) ✨',
    'msc_calc.exams_entered': 'Esami inseriti',
    'msc_calc.credits': 'Crediti',
    'msc_calc.enter_grades': 'Inserisci voti',
    'msc_calc.thesis_points': 'Punti Tesi',
    'msc_calc.thesis_tooltip': 'Punti assegnati dalla commissione per la tesi di laurea magistrale (0-8 punti).',
    'msc_calc.bonus_points': 'Bonus Aggiuntivi',
    'msc_calc.bonus_tooltip': 'Bonus per exchange, tirocinio o attività extracurriculari. Inserisci un valore numerico.',
    'msc_calc.points': 'punti',
    'msc_calc.exams_title': 'Esami',
    'msc_calc.grade': 'Voto',
    'msc_calc.select_grade': 'Seleziona voto',
    'msc_calc.pass_fail': 'Pass/Fail - Nessun voto richiesto',
    'msc_calc.loading': 'Caricamento esami...',
    'msc_calc.disclaimer': '⚠️ Questo è uno strumento di stima. Il voto finale di laurea è determinato dalla commissione di Bocconi.',
    'msc_calc.thesis_note': 'Nota: La tesi è inclusa automaticamente nel calcolo dei crediti',
    
    // Marketplace Section
    'marketplace.title': 'ASTRA x UniMarket',
    'marketplace.subtitle': 'Il marketplace ufficiale per studenti Bocconi. Merchandising esclusivo e prodotti essenziali per la vita universitaria.',
    'marketplace.features.exchange': 'Scambio Veloce',
    'marketplace.features.exchange.description': 'Incontra il venditore direttamente in università',
    'marketplace.features.community': 'Community Sicura',
    'marketplace.features.community.description': 'Accesso riservato agli studenti universitari',
    'marketplace.features.commission': 'Zero Commissioni',
    'marketplace.features.commission.description': 'Scambia o vendi gratuitamente',
    'marketplace.add': 'Aggiungi',
    'marketplace.cta.title': 'Scopri il Marketplace Completo',
    'marketplace.cta.button': 'Visita UniMarket',
    'marketplace.cta.description': 'Oltre 200 prodotti esclusivi per studenti. Libri usati, merchandising ufficiale, gadget tech e molto altro.',
    
    // Events Section
    'events.title': 'Eventi e Conferenze',
    'events.subtitle': 'Partecipa agli eventi ASTRA. Workshop, conferenze e networking per arricchire la tua esperienza universitaria.',
    'events.upcoming': 'Prossimi Eventi',
    'events.past': 'Eventi Passati',
    'events.loading': 'Caricamento eventi...',
    'events.no-upcoming': 'Nessun evento prossimo disponibile',
    'events.no-past': 'Nessun evento passato disponibile',
    'events.register': 'Registrati all\'Evento',
    'events.registration-unavailable': 'Registrazione non disponibile',
    'events.add-calendar': 'Aggiungi al Calendario',
    
    // Footer
    'footer.rights': 'Tutti i diritti riservati.',
    'footer.resources': 'Risorse',
    'footer.support': 'Supporto',
    'footer.social': 'Social',
    'footer.handouts': 'Dispense',
    'footer.calculators': 'Calcolatori',
    'footer.guides': 'Guide',
    'footer.contact': 'Contattaci',
    'footer.faq': 'FAQ',
    'footer.privacy': 'Privacy Policy',
    'footer.address': 'Indirizzo:',
    'footer.addressValue': 'Via Sarfatti 5, Milano (MI)',
    'footer.email': 'Email:',
    'footer.legal': 'Legal',
    'footer.copyright': 'Copyright © 2026 Astra Bocconi',
    'footer.developedBy': 'sviluppato da Michele F. Matozza',
    
    // Guide Categories
    'guide.title': 'Guide Universitarie',
    'guide.subtitle': 'Le nostre guide, dagli studenti per gli studenti. Seleziona una categoria per esplorare le guide disponibili.',
    'guide.explore': 'Esplora Guide',
    'guide.backToGuides': 'Torna alle Guide',
    'guide.backToHome': 'Torna alla Home',
    'guide.exploreAll': 'Esplora tutte le guide disponibili per questa categoria',
    'guide.noGuides': 'Nessuna guida trovata',
    'guide.noGuidesDescription': 'Non sono ancora disponibili guide per questa categoria.',
    'guide.noCategories': 'Nessuna categoria trovata',
    'guide.noCategoriesDescription': 'Non sono ancora disponibili guide.',
    
    // Guide Category Titles
    'category.associations.title': 'Associations',
    'category.associations.description': 'Scopri le associazioni Bocconi!',
    'category.opzionali.title': 'Opzionali',
    'category.opzionali.description': 'Guide per la scelta dei tuoi opzionali',
    'category.graduate.title': 'Graduate',
    'category.graduate.description': 'Le nostre guide per la tua magistrale',
    'category.stage.title': 'Stage',
    'category.stage.description': 'Le nostre guide per il tuo stage',
    'category.freemover.title': 'Freemover',
    'category.freemover.description': 'Le nostre guide per il freemover',
    'category.residenze.title': 'Residenze',
    'category.residenze.description': 'Guide per le residenze degli studenti',
    'category.exchange_magistrale.title': 'Exchange Magistrale',
    'category.exchange_magistrale.description': 'Guide per il tuo exchange magistrale',
    'category.exchange_triennale.title': 'Exchange Triennale',
    'category.exchange_triennale.description': 'Guide per il tuo exchange triennale',
    'category.university.title': 'University',
    'category.university.description': 'Guide al primo anno di Università',
    'category.milan.title': 'Milan',
    'category.milan.description': 'Scopri Milano prima di trasferirti',
    'category.burocrazia.title': 'Burocrazia',
    'category.burocrazia.description': 'Come districarsi nella burocrazia italiana',
    'category.master_admissions.title': 'Master Admissions',
    'category.master_admissions.description': 'Guide per le ammissioni magistrali',
    'category.tesi.title': 'Tesi',
    'category.tesi.description': 'Guida per la tesi triennale',
    'category.ecdl.title': 'ECDL',
     'category.ecdl.description': 'Tutto quello che devi sapere',
    'category.spring weeks.title': 'Spring Weeks',
    'category.spring weeks.description': 'Scopri le spring weeks disponibili',
    'category.funding.title': 'Funding',
    'category.funding.description': 'Opportunità di finanziamento disponibili',
    'category.linkedin.title': 'LinkedIn',
    'category.linkedin.description': 'Consigli e guide per il tuo profilo LinkedIn',
    'category.languages.title': 'Lingue',
    'category.languages.description': 'Esercizi e materiali per imparare le lingue',
    'category.languages.pageTitle': 'Lingue: esercizi e materiali per le tue lingue!',
    'category.bgl_domestic_track.title': 'BGL Domestic Track',
    'category.bgl_domestic_track.description': 'Guida al percorso BGL Domestic Track',
    'category.program_change.title': 'Cambio Corso Triennale',
    'category.program_change.description': 'Guida al cambio corso triennale',
    'category.magistrali.title': 'Magistrali',
    'category.magistrali.description': 'Guide per le lauree magistrali',
    'category.magistrali.pageTitle': 'Magistrali: le nostre guide per le lauree magistrali!',

    // Guide Category Page
    'guideCategory.backToGuides': 'Torna alle Guide',
    'guideCategory.subtitle': 'Esplora tutte le guide disponibili per questa categoria',
    'guideCategory.noGuides': 'Nessuna guida trovata',
    'guideCategory.noGuidesDescription': 'Non sono ancora disponibili guide per questa categoria.',
    'category.associations.pageTitle': 'Associations: scopri le associazioni Bocconi!',
    'category.opzionali.pageTitle': 'Opzionali 101: le nostre guide per la scelta dei tuoi opzionali!',
    'category.graduate.pageTitle': 'Graduate 101: le nostre guide per la tua magistrale!',
    'category.stage.pageTitle': 'Stage 101: le nostre guide per il tuo stage!',
    'category.spring weeks.pageTitle': 'Spring Weeks: scopri le spring weeks disponibili!',
    'category.freemover.pageTitle': 'Freemover 101: le nostre guide per il freemover!',
    'category.residenze.pageTitle': 'Residenze 101: le nostre guide per le residenze!',
    'category.exchange_magistrale.pageTitle': 'Exchange 101: guide per il tuo exchange magistrale!',
    'category.exchange_triennale.pageTitle': 'Exchange 101: guide per il tuo exchange triennale!',
    'category.university.pageTitle': 'University 101: guide al primo anno di Università!',
    'category.milan.pageTitle': 'Milan 101: scopri Milano prima di trasferirti!',
    'category.burocrazia.pageTitle': 'Burocrazia 101: come districarsi nella burocrazia italiana!',
    'category.master_admissions.pageTitle': 'Master Admissions',
    'category.tesi.pageTitle': 'Tesi 101: guida per la tesi triennale',
    'category.ecdl.pageTitle': 'ECDL 101: tutto quello che devi sapere',
    'category.funding.pageTitle': 'Funding: scopri le opportunità di finanziamento!',
    'category.linkedin.pageTitle': 'LinkedIn: le nostre guide per il tuo profilo LinkedIn!',

    // Dispense Section
    'dispense.title': 'Dispense Universitarie',
    'dispense.subtitle': 'Accedi alle dispense organizzate per corso. Materiali di studio condivisi dalla comunità studentesca.',
    'dispense.accessHandouts': 'Accedi alle Dispense',
    'dispense.selectYear': 'Seleziona l\'anno accademico per visualizzare le dispense disponibili',

    // CLMG Section
    'clmg.title': 'CLMG - Giurisprudenza',
    'clmg.subtitle': 'Dispense e materiali per il corso di laurea magistrale in Giurisprudenza. Seleziona l\'anno di interesse.',
    'clmg.firstYear': 'Primo Anno',
    'clmg.secondYear': 'Secondo Anno',
    'clmg.thirdYear': 'Terzo Anno',
    'clmg.fourthYear': 'Quarto Anno',
    'clmg.fifthYear': 'Quinto Anno',
    'clmg.materialsForYear': 'Materiali di studio',
    'clmg.accessHandouts': 'Accedi alle Dispense',
    'clmg.backToCLMG': 'Torna a CLMG',
    'clmg.handoutsForText': 'Dispense per',
    'clmg.searchPlaceholder': 'Cerca per nome file...',
    'clmg.loading': 'Caricamento dispense...',
    'clmg.noHandouts': 'Nessuna dispensa disponibile',
    'clmg.noHandoutsText': 'Non sono ancora disponibili dispense per',
    'clmg.noSearchResults': 'Nessun risultato trovato',
    'clmg.noSearchResultsText': 'Nessuna dispensa trovata per',
    'clmg.uploadedOn': 'Caricato il',
    'clmg.download': 'Scarica',
    'clmg.downloadStarted': 'Download avviato',
    'clmg.errorFetching': 'Errore nel caricamento delle dispense',
    'clmg.yearNotFound': 'Anno non trovato',
    'clmg.oneResult': '1 dispensa trovata',
    'clmg.multipleResultsText': 'dispense trovate',

    // Women's Day Section
    'womensDay.badge': '🌼 8 Marzo 2026 — Giornata Internazionale della Donna 🌼',
    'womensDay.title': 'Il Ruolo della Donna',
    'womensDay.description': 'Leggi l\'articolo completo per scoprire riflessioni, storie e prospettive sul contributo fondamentale delle donne nel mondo di oggi.',
    'womensDay.cta': 'Leggi l\'Articolo',

    // Free@B Section
    'freeatb.subtitle': 'Uno strumento che ti permette di trovare aule libere in tempo reale alla Bocconi.',
    'freeatb.feature1.title': 'Scegli edificio, giorno e ora',
    'freeatb.feature1.description': 'Seleziona i tuoi criteri per trovare l\'aula perfetta per te.',
    'freeatb.feature2.title': 'Trova aule libere istantaneamente',
    'freeatb.feature2.description': 'Visualizza tutte le aule disponibili in un solo click.',
    'freeatb.feature3.title': 'Accesso rapido e aggiornamenti live',
    'freeatb.feature3.description': 'Dati sempre aggiornati in tempo reale per non perdere nessuno spazio.',
    'freeatb.cta.title': 'Trova la tua aula libera ora',
    'freeatb.cta.description': 'Perfetto per studiare tra una lezione e l\'altra, incontrare il tuo gruppo, o semplicemente trovare un posto tranquillo in campus.',
    'freeatb.cta.button': 'Vai a Free@B',

    // CourseHandouts
    'courseHandouts.backToCourse': 'Torna al Corso',
    'courseHandouts.availableHandouts': 'Dispense disponibili per questo corso',
    'courseHandouts.searchPlaceholder': 'Cerca dispense...',
    'courseHandouts.loading': 'Caricamento dispense...',
    'courseHandouts.noResults': 'Nessuna dispensa trovata',
    'courseHandouts.noResultsSearch': 'Nessun risultato per',
    'courseHandouts.noResultsEmpty': 'Le dispense per questo corso non sono ancora disponibili.',
    'courseHandouts.courseHandouts': 'Dispense del Corso',
    'courseHandouts.errorLoading': 'Impossibile caricare le dispense',
    'courseHandouts.errorGeneric': 'Errore nel caricamento delle dispense',
    'courseHandouts.fileUnavailable': 'URL del file non disponibile',
    'courseHandouts.all': 'Tutti',
    'courseHandouts.semester1': '1° Semestre',
    'courseHandouts.semester2': '2° Semestre',
    'courseHandouts.filterSemester': 'Filtra per semestre',
    'courseHandouts.filterExamType': 'Filtra per tipo di esame',
    'courseHandouts.parziale': 'Parziale',
    'courseHandouts.generale': 'Generale',

    // Year Pages
    'yearPage.firstYear': 'Primo Anno',
    'yearPage.secondYear': 'Secondo Anno',
    'yearPage.thirdYear': 'Terzo Anno',
    'yearPage.backToHandouts': 'Torna alle Dispense',
    'yearPage.accessHandouts': 'Accedi alle dispense e materiali didattici per i corsi del',
    'yearPage.noCourses': 'Nessun corso trovato',
    'yearPage.noHandoutsAvailable': 'Non sono ancora disponibili dispense per il',
    'yearPage.viewHandouts': 'Visualizza le dispense disponibili per questo corso',
    'yearPage.files': 'file',

    // Common
    'common.loading': 'Caricamento...',
    'common.error': 'Errore',
    'common.unexpectedError': 'Si è verificato un errore imprevisto',
    'common.categoryNotFound': 'Categoria non trovata',
    'common.readMore': 'Leggi di più',
    'common.learnMore': 'Scopri di più',
    'common.backToDispense': 'Torna alle Dispense',
    'common.backToHome': 'Torna alla Home',

    // Stella Polare
    'stellapolare.subtitle': 'Tutte le rubriche redatte dai nostri ragazzi della divisione Press!',
    'stellapolare.podcast': 'Ascolta il nostro Podcast su YouTube',
    'stellapolare.weekly': 'Settimanale',
    'stellapolare.monthly': 'Mensile',
    'stellapolare.podcastBtn': 'Podcast',
    'stellapolare.noArticles': 'Nessun articolo disponibile per questa categoria.',
    'stellapolare.article': 'Articolo',
    'stellapolare.back': 'Indietro',
    'stellapolare.weeklyTitle': 'Rubriche Settimanali',
    'stellapolare.weeklySubtitle': 'Scegli un tema per esplorare le rubriche',
    'stellapolare.monthlyTitle': 'Rubriche Mensili',
    'stellapolare.theme.arte': 'Arte, Cultura, Cinema e Teatro',
    'stellapolare.theme.economia': 'Economia',
    'stellapolare.theme.international': 'International',
    'stellapolare.theme.legal': 'Legal',
    'stellapolare.theme.sport': 'Sport',
    'stellapolare.theme.astranews': 'Astra News',
  },
  en: {
    // Navigation
    'nav.representatives': 'Representatives',
    'nav.handouts': 'Handouts',
    'nav.exchange': 'Exchange',
    'nav.directory': 'Directory',
    'nav.guides': 'Guides',
    'nav.about': 'About Us',
    'nav.calculators': 'Calculators',
    
    // Hero Section
    'hero.subtitle': 'Your reference student association at Bocconi. Discover all the services and opportunities we provide to make your university experience unforgettable.',
    'hero.aboutUs': 'About Us',
    'hero.contact': 'Contact Us',
    'board.title': 'Our Board',
    
    // About Section
    'about.title': 'About Us',
    'about.subtitle': 'ASTRA is the student association that represents Bocconi students, offering services, support and opportunities to improve everyone\'s university experience.',
    'about.innovation.title': 'Innovation',
    'about.innovation.description': 'We promote innovative solutions to improve the university experience through technology and creativity.',
    'about.community.title': 'Community',
    'about.community.description': 'We build a strong and collaborative community that supports every student in achieving their goals.',
    'about.future.title': 'Future',
    'about.future.description': 'We prepare students for their professional future with concrete opportunities and personalized guidance.',
    
    // Values Section
    'values.title': 'Our Values',
    'values.subtitle': 'The principles that guide every action and decision we make',
    'values.ambition.title': 'Ambition',
    'values.ambition.description': 'It\'s not careerism, but the will to push beyond. Looking ahead, seeking better solutions and never stopping.',
    'values.communication.title': 'Communication',
    'values.communication.description': 'Ideas are only valuable if they are heard. Dialogue between students and University is the key to building real change.',
    'values.dedication.title': 'Dedication',
    'values.dedication.description': 'Nothing is achieved without perseverance and commitment. Only those who put themselves on the line every day can make a mark.',
    
    // What We Do Section
    'whatwedo.title': 'What We Do',
    'whatwedo.subtitle': 'Our vision of representation develops through three fundamental aspects of the university experience',
    'whatwedo.handouts.title': 'Handouts and Materials',
    'whatwedo.handouts.description': 'Facilitated access to handouts, notes and study materials for all courses',
    'whatwedo.exchange.title': 'Exchange Program',
    'whatwedo.exchange.description': 'Complete support for international exchange programs and opportunities abroad',
    'whatwedo.representation.title': 'Active Representation',
    'whatwedo.representation.description': 'Your voice in university bodies to improve everyone\'s experience',
    'whatwedo.innovation.title': 'Educational Innovation',
    'whatwedo.innovation.description': 'We promote new learning methods and technologies for education',
    'whatwedo.career.title': 'Career Guidance',
    'whatwedo.career.description': 'Guides and support to build your professional path',
    'whatwedo.wellbeing.title': 'Student Wellbeing',
    'whatwedo.wellbeing.description': 'Initiatives for psychophysical wellbeing and study-life balance',
    'whatwedo.approach.title': 'A 360° approach to your university experience',
    'whatwedo.approach.description': 'We are not limited to traditional representation. We create a support ecosystem that accompanies every student from day one to graduation, building a strong and collaborative community.',
    
    // Team Section
    'team.title': 'Our Team',
    'team.subtitle': 'Meet the representatives who work to improve your university experience. A diverse team with complementary skills.',
    'team.search': 'Search by name, role or course...',
    'team.all': 'all',
    'team.presidency': 'Presidency',
    'team.senate': 'Academic Senate',
    'team.events': 'Events',
    'team.innovation': 'Innovation',
    'team.communication': 'Communication',
    'team.exchange': 'Exchange',
    'team.welfare': 'Welfare',
    'team.no-results': 'No members found with current filters.',
    'team.stats.representatives': 'Active Representatives',
    'team.stats.bodies': 'Represented Bodies',
    'team.stats.courses': 'Degree Courses',
    'team.stats.students': 'Represented Students',
    
    // Representatives Section
    'representatives.title': '🏛️ Our Representatives',
    'representatives.subtitle': 'Discover the different areas of student representation. Our representatives work in various bodies and commissions to protect your rights and improve university life.',
    'representatives.loading': 'Loading representatives...',
    'representatives.viewReps': 'View Representatives',
    'representatives.hide': 'Hide',
    'representatives.learnMore': 'Learn More',
    'representatives.count': 'representative',
    'representatives.countSingle': '',
    'representatives.countPlural': 's',
    'representatives.noReps': 'No representatives currently available for this section.',
    'representatives.cdd.description': 'Teaching Discipline Commission - Management of disciplinary and teaching matters',
    'representatives.dipartimenti.description': 'Representation in the university\'s various academic departments',
    'representatives.isu.description': 'Institute for University Support - Services for the right to study',
    'representatives.qualita.description': 'Quality Commission - Monitoring and improvement of teaching quality',
    'representatives.giurisprudenza.description': 'Representation in the School of Law',
    'representatives.magistrale.description': 'Representation in master\'s schools and master\'s degree courses',
    'representatives.triennale.description': 'Representation in bachelor\'s schools and bachelor\'s degree courses',
    'representatives.sport.description': 'Representation in university sports and recreational activities',
    'representatives.valutazione.description': 'Evaluation Commission - Assessment of academic performance',
    
    // Handouts Section
    'handouts.title': 'Handouts and Guides',
    'handouts.subtitle': 'Access study resources shared by the community. Find handouts, summaries and guides for every course.',
    'handouts.search': 'Search by subject or file name...',
    'handouts.firstYear': '1st Year',
    'handouts.secondYear': '2nd Year',
    'handouts.thirdYear': '3rd Year',
    'handouts.loading': 'Loading handouts...',
    'handouts.uploaded': 'Uploaded:',
    'handouts.download': 'Download PDF',
    'handouts.seeAll': 'See all handouts for',
    'handouts.seeAllGeneral': 'See all handouts',
    'handouts.results': 'result',
    'handouts.resultsFound': 'found for',
    'handouts.noResults': 'No handouts',
    'handouts.noResultsSearch': 'found for',
    'handouts.noResultsYear': 'available for',
    
    // Astra Polare Section
    'astrapolare.title': 'Astra Polare',
    'astrapolare.subtitle': 'Our digital magazine. Content, stories and media that tell university life from the students\' perspective.',
    'astrapolare.recent': 'Most Recent',
    'astrapolare.popular': 'Most Viewed',
    'astrapolare.trending': 'Trending',
    'astrapolare.loading': 'Loading content...',
    'astrapolare.error': 'Error loading content',
    'astrapolare.retry': 'Retry',
    'astrapolare.noContent': 'No content available at the moment.',
    'astrapolare.slides': 'slides',
    'astrapolare.views': 'views',
    'astrapolare.visualizations': 'views',
    'astrapolare.followSocial': 'Follow Us on Social Media',
    'astrapolare.followDescription': 'Don\'t miss our content! Follow us on TikTok and Instagram to stay updated.',
    'astrapolare.tiktok': '📱 TikTok',
    'astrapolare.instagram': '📸 Instagram',
    
    // Astra GPT Section
    'astragpt.title': 'Astra GPT',
    'astragpt.powered': 'Powered by AI',
    'astragpt.subtitle': 'Your intelligent virtual assistant to navigate Bocconi university life. Always available, always updated.',
    'astragpt.description': 'Discover the new AstraGPT 2.0 - powered by the most advanced artificial intelligence to support you in your Bocconi university life.',
    'astragpt.try': 'Try Astra GPT 2.0!',
    'astragpt.open': 'Open AstraGPT 2.0',
    
    // Calculators Section
    'calculators.title': 'Smart Calculators',
    'calculators.subtitle': 'Intelligent tools to optimize your university journey. Plan, calculate and achieve your academic goals.',
    'calculators.gpa.title': 'GPA & Graduation Score (Undergraduate)',
    'calculators.gpa.description': 'Calculate your expected graduation grade based on your exams',
    'calculators.gpa-msc.title': 'GPA & Graduation Score (MSc)',
    'calculators.gpa-msc.description': 'Calculate your MSc graduation grade with thesis and bonus points',
    'calculators.exchange-msc.title': 'Exchange Calculator MSc',
    'calculators.exchange-msc.description': 'Calculate your Exchange Score and discover available destinations',
    'calculators.exchange-clmg.title': 'Exchange Calculator CLMG',
    'calculators.exchange-clmg.description': 'Calculate your score for exchange in Law',
    'calculators.exchange-ug.title': 'Exchange Calculator UG',
    'calculators.exchange-ug.description': 'Calculate your Exchange Score for Undergraduate',
    'calculators.features': 'Features:',
    'calculators.use': 'Use Calculator',
    'calculators.feat.gpa.1': 'Graduation grade out of 110',
    'calculators.feat.gpa.2': 'GPA out of 30',
    'calculators.feat.gpa.3': 'Configurable bonuses',
    'calculators.feat.exchange.1': 'Exchange Score calculation',
    'calculators.feat.exchange.2': 'Destinations by continent',
    'calculators.feat.exchange.3': 'Acceptance Rate',
    
    // MSc Calculator
    'msc_calc.select_course': 'Select Master\'s Degree',
    'msc_calc.select_course_placeholder': 'Choose your master\'s degree',
    'msc_calc.select_track': 'Select Track',
    'msc_calc.select_track_placeholder': 'Choose your track',
    'msc_calc.gpa_tooltip': 'Weighted average of grades by credits. "30 e lode" = 30 in calculation.',
    'msc_calc.base_score': 'Base Score',
    'msc_calc.base_score_tooltip': 'Conversion to 110 scale: (GPA / 30) × 110',
    'msc_calc.graduation_grade': 'Graduation Grade',
    'msc_calc.graduation_tooltip': 'Base score + thesis points + bonus. If ≥ 110 → Eligible for 110 e Lode.',
    'msc_calc.out_of_30': 'out of 30',
    'msc_calc.out_of_110': 'out of 110',
    'msc_calc.lode_badge': 'Eligible for 110 e Lode (subject to committee approval) ✨',
    'msc_calc.exams_entered': 'Exams entered',
    'msc_calc.credits': 'Credits',
    'msc_calc.enter_grades': 'Enter grades',
    'msc_calc.thesis_points': 'Thesis Points',
    'msc_calc.thesis_tooltip': 'Points awarded by the committee for the master\'s thesis (0-8 points).',
    'msc_calc.bonus_points': 'Additional Bonus',
    'msc_calc.bonus_tooltip': 'Bonus for exchange, internship or extracurricular activities. Enter a numeric value.',
    'msc_calc.points': 'points',
    'msc_calc.exams_title': 'Exams',
    'msc_calc.grade': 'Grade',
    'msc_calc.select_grade': 'Select grade',
    'msc_calc.pass_fail': 'Pass/Fail - No grade required',
    'msc_calc.loading': 'Loading exams...',
    'msc_calc.disclaimer': '⚠️ This is an estimation tool. The final graduation grade is determined by the Bocconi committee.',
    'msc_calc.thesis_note': 'Note: The thesis is automatically included in the credit calculation',
    
    // Marketplace Section
    'marketplace.title': 'ASTRA x UniMarket',
    'marketplace.subtitle': 'The official marketplace for Bocconi students. Exclusive merchandise and essential products for university life.',
    'marketplace.features.exchange': 'Quick Exchange',
    'marketplace.features.exchange.description': 'Meet the seller directly at university',
    'marketplace.features.community': 'Safe Community',
    'marketplace.features.community.description': 'Access reserved for university students',
    'marketplace.features.commission': 'Zero Commissions',
    'marketplace.features.commission.description': 'Trade or sell for free',
    'marketplace.add': 'Add',
    'marketplace.cta.title': 'Discover the Complete Marketplace',
    'marketplace.cta.button': 'Visit UniMarket',
    'marketplace.cta.description': 'Over 200 exclusive products for students. Used books, official merchandise, tech gadgets and much more.',

    // Free@B Section
    'freeatb.subtitle': 'A tool that lets you find available classrooms in real time at Bocconi.',
    'freeatb.feature1.title': 'Choose building, day and time',
    'freeatb.feature1.description': 'Select your criteria to find the perfect room for you.',
    'freeatb.feature2.title': 'Find all free rooms instantly',
    'freeatb.feature2.description': 'View all available classrooms in just one click.',
    'freeatb.feature3.title': 'Fast access and live updates',
    'freeatb.feature3.description': 'Always up-to-date real-time data so you never miss a spot.',
    'freeatb.cta.title': 'Find your free classroom now',
    'freeatb.cta.description': 'Perfect for studying between classes, meeting your group, or just finding a quiet spot on campus.',
    'freeatb.cta.button': 'Go to Free@B',
    
    // Events Section
    'events.title': 'Events and Conferences',
    'events.subtitle': 'Participate in ASTRA events. Workshops, conferences and networking to enrich your university experience.',
    'events.upcoming': 'Upcoming Events',
    'events.past': 'Past Events',
    'events.loading': 'Loading events...',
    'events.no-upcoming': 'No upcoming events available',
    'events.no-past': 'No past events available',
    'events.register': 'Register for Event',
    'events.registration-unavailable': 'Registration not available',
    'events.add-calendar': 'Add to Calendar',
    
    // Footer
    'footer.rights': 'All rights reserved.',
    'footer.resources': 'Resources',
    'footer.support': 'Support',
    'footer.social': 'Social',
    'footer.handouts': 'Handouts',
    'footer.calculators': 'Calculators',
    'footer.guides': 'Guides',
    'footer.contact': 'Contact Us',
    'footer.faq': 'FAQ',
    'footer.privacy': 'Privacy Policy',
    'footer.address': 'Address:',
    'footer.addressValue': 'Via Sarfatti 5, Milan (MI)',
    'footer.email': 'Email:',
    'footer.legal': 'Legal',
    'footer.copyright': 'Copyright © 2026 Astra Bocconi',
    'footer.developedBy': 'developed by Michele F. Matozza',
    
    // Guide Categories
    'guide.title': 'University Guides',
    'guide.subtitle': 'Our guides, from students for students. Select a category to explore available guides.',
    'guide.explore': 'Explore Guides',
    'guide.backToGuides': 'Back to Guides',
    'guide.backToHome': 'Back to Home',
    'guide.exploreAll': 'Explore all available guides for this category',
    'guide.noGuides': 'No guides found',
    'guide.noGuidesDescription': 'No guides are available for this category yet.',
    'guide.noCategories': 'No categories found',
    'guide.noCategoriesDescription': 'No guides are available yet.',
    
    // Guide Category Titles
    'category.associations.title': 'Associations',
    'category.associations.description': 'Discover Bocconi associations!',
    'category.opzionali.title': 'Optional Courses',
    'category.opzionali.description': 'Guides for choosing your electives',
    'category.graduate.title': 'Graduate',
    'category.graduate.description': 'Our guides for your Master\'s degree',
    'category.stage.title': 'Internship',
    'category.stage.description': 'Our guides for your internship',
    'category.freemover.title': 'Freemover',
    'category.freemover.description': 'Our guides for freemover programs',
    'category.residenze.title': 'Residences',
    'category.residenze.description': 'Guides for student residences',
    'category.exchange_magistrale.title': 'Exchange Master\'s',
    'category.exchange_magistrale.description': 'Guides for your Master\'s exchange',
    'category.exchange_triennale.title': 'Exchange Bachelor\'s',
    'category.exchange_triennale.description': 'Guides for your Bachelor\'s exchange',
    'category.university.title': 'University',
    'category.university.description': 'Guides for your first year at University',
    'category.milan.title': 'Milan',
    'category.milan.description': 'Discover Milan before moving here',
    'category.burocrazia.title': 'Bureaucracy',
    'category.burocrazia.description': 'How to navigate Italian bureaucracy',
    'category.master_admissions.title': 'Master Admissions',
    'category.master_admissions.description': 'Guides for Master\'s admissions',
    'category.tesi.title': 'Thesis',
    'category.tesi.description': 'Guide for your Bachelor\'s thesis',
    'category.ecdl.title': 'ECDL',
    'category.ecdl.description': 'Everything you need to know',
    'category.spring weeks.title': 'Spring Weeks',
    'category.spring weeks.description': 'Discover available spring weeks',
    'category.funding.title': 'Funding',
    'category.funding.description': 'Available funding opportunities',
    'category.linkedin.title': 'LinkedIn',
    'category.linkedin.description': 'Tips and guides for your LinkedIn profile',
    'category.languages.title': 'Languages',
    'category.languages.description': 'Exercises and materials to learn languages',
    'category.languages.pageTitle': 'Languages: exercises and materials for your languages!',
    'category.bgl_domestic_track.title': 'BGL Domestic Track',
    'category.bgl_domestic_track.description': 'Guide to the BGL Domestic Track path',
    'category.program_change.title': 'Program Change Undergraduate',
    'category.program_change.description': 'Guide to changing your undergraduate program',

    // Guide Category Page
    'guideCategory.backToGuides': 'Back to Guides',
    'guideCategory.subtitle': 'Explore all available guides for this category',
    'guideCategory.noGuides': 'No guides found',
    'guideCategory.noGuidesDescription': 'No guides are available for this category yet.',
    'category.associations.pageTitle': 'Associations: discover Bocconi associations!',
    'category.opzionali.pageTitle': 'Optional Courses 101: guides for choosing your electives!',
    'category.graduate.pageTitle': 'Graduate 101: our guides for your Master\'s degree!',
    'category.stage.pageTitle': 'Internship 101: our guides for your internship!',
    'category.spring weeks.pageTitle': 'Spring Weeks: discover available spring weeks!',
    'category.freemover.pageTitle': 'Freemover 101: our guides for freemover programs!',
    'category.residenze.pageTitle': 'Residences 101: our guides for student residences!',
    'category.exchange_magistrale.pageTitle': 'Exchange 101: guides for your Master\'s exchange!',
    'category.exchange_triennale.pageTitle': 'Exchange 101: guides for your Bachelor\'s exchange!',
    'category.university.pageTitle': 'University 101: guides for your first year!',
    'category.milan.pageTitle': 'Milan 101: discover Milan before moving here!',
    'category.burocrazia.pageTitle': 'Bureaucracy 101: navigating Italian bureaucracy!',
    'category.master_admissions.pageTitle': 'Master Admissions',
    'category.tesi.pageTitle': 'Thesis 101: guide for your Bachelor\'s thesis',
    'category.ecdl.pageTitle': 'ECDL 101: everything you need to know',
    'category.funding.pageTitle': 'Funding: discover available funding opportunities!',
    'category.linkedin.pageTitle': 'LinkedIn: our guides for your LinkedIn profile!',

    // Dispense Section
    'dispense.title': 'University Handouts',
    'dispense.subtitle': 'Access handouts organized by course. Study materials shared by the student community.',
    'dispense.accessHandouts': 'Access Handouts',
    'dispense.selectYear': 'Select the academic year to view available handouts',
    
    // CLMG Section
    'clmg.title': 'CLMG - Law',
    'clmg.subtitle': 'Handouts and materials for the Law Master\'s degree program. Select the year of interest.',
    'clmg.firstYear': 'First Year',
    'clmg.secondYear': 'Second Year',
    'clmg.thirdYear': 'Third Year',
    'clmg.fourthYear': 'Fourth Year',
    'clmg.fifthYear': 'Fifth Year',
    'clmg.materialsForYear': 'Study materials',
    'clmg.accessHandouts': 'Access Handouts',
    'clmg.backToCLMG': 'Back to CLMG',
    'clmg.handoutsForText': 'Handouts for',
    'clmg.searchPlaceholder': 'Search by filename...',
    'clmg.loading': 'Loading handouts...',
    'clmg.noHandouts': 'No handouts available',
    'clmg.noHandoutsText': 'No handouts available yet for',
    'clmg.noSearchResults': 'No results found',
    'clmg.noSearchResultsText': 'No handouts found for',
    'clmg.uploadedOn': 'Uploaded on',
    'clmg.download': 'Download',
    'clmg.downloadStarted': 'Download started',
    'clmg.errorFetching': 'Error loading handouts',
    'clmg.yearNotFound': 'Year not found',
    'clmg.oneResult': '1 handout found',
    'clmg.multipleResultsText': 'handouts found',
    
    // Women's Day Section
    'womensDay.badge': '🌼 March 8, 2026 — International Women\'s Day 🌼',
    'womensDay.title': 'The Role of Women',
    'womensDay.description': 'Read the full article to discover reflections, stories, and perspectives on the fundamental contribution of women in today\'s world.',
    'womensDay.cta': 'Read the Article',

    // CourseHandouts
    'courseHandouts.backToCourse': 'Back to Course',
    'courseHandouts.availableHandouts': 'Available handouts for this course',
    'courseHandouts.searchPlaceholder': 'Search handouts...',
    'courseHandouts.loading': 'Loading handouts...',
    'courseHandouts.noResults': 'No handouts found',
    'courseHandouts.noResultsSearch': 'No results for',
    'courseHandouts.noResultsEmpty': 'Handouts for this course are not yet available.',
    'courseHandouts.courseHandouts': 'Course Handouts',
    'courseHandouts.errorLoading': 'Unable to load handouts',
    'courseHandouts.errorGeneric': 'Error loading handouts',
    'courseHandouts.fileUnavailable': 'File URL not available',
    'courseHandouts.all': 'All',
    'courseHandouts.semester1': '1st Semester',
    'courseHandouts.semester2': '2nd Semester',
    'courseHandouts.filterSemester': 'Filter by semester',
    'courseHandouts.filterExamType': 'Filter by exam type',
    'courseHandouts.parziale': 'Partial',
    'courseHandouts.generale': 'General',

    // Year Pages
    'yearPage.firstYear': 'First Year',
    'yearPage.secondYear': 'Second Year',
    'yearPage.thirdYear': 'Third Year',
    'yearPage.backToHandouts': 'Back to Handouts',
    'yearPage.accessHandouts': 'Access handouts and study materials for',
    'yearPage.noCourses': 'No courses found',
    'yearPage.noHandoutsAvailable': 'No handouts available yet for',
    'yearPage.viewHandouts': 'View available handouts for this course',
    'yearPage.files': 'file',

    // Common
    'common.loading': 'Loading...',
    'common.error': 'Error',
    'common.unexpectedError': 'An unexpected error occurred',
    'common.categoryNotFound': 'Category not found',
    'common.readMore': 'Read more',
    'common.learnMore': 'Learn more',
    'common.backToDispense': 'Back to Handouts',
    'common.backToHome': 'Back to Home',

    // Stella Polare
    'stellapolare.subtitle': 'All the columns written by our Press division team!',
    'stellapolare.podcast': 'Listen to our Podcast on YouTube',
    'stellapolare.weekly': 'Weekly',
    'stellapolare.monthly': 'Monthly',
    'stellapolare.podcastBtn': 'Podcast',
    'stellapolare.noArticles': 'No articles available for this category.',
    'stellapolare.article': 'Article',
    'stellapolare.back': 'Back',
    'stellapolare.weeklyTitle': 'Weekly Columns',
    'stellapolare.weeklySubtitle': 'Pick a theme to explore the columns',
    'stellapolare.monthlyTitle': 'Monthly Columns',
    'stellapolare.theme.arte': 'Art, Culture, Cinema & Theatre',
    'stellapolare.theme.economia': 'Economics',
    'stellapolare.theme.international': 'International',
    'stellapolare.theme.legal': 'Legal',
    'stellapolare.theme.sport': 'Sport',
    'stellapolare.theme.astranews': 'Astra News',
  }
};

export const LanguageProvider: React.FC<LanguageProviderProps> = ({ children }) => {
  const [language, setLanguage] = useState<Language>('it');

  const t = (key: string): string => {
    return translations[language][key as keyof typeof translations['it']] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};