import { StellaPolareArticleLayout } from "@/components/ui/stella-polare-article-layout";

export default function StellaPolareArticleAgroalimentare() {
  return (
    <StellaPolareArticleLayout
      eyebrow="Legal · Aprile 2026"
      title="Impresa e Governance Agroalimentare: il futuro del food italiano"
    >
      <p>
        Il 23 aprile Astra Bocconi, la Corporate Law Academy e INSUD hanno avuto il piacere di tenere la conferenza <em>Impresa e Governance Agroalimentare – Il futuro del food italiano</em> presso l'Università Bocconi. Nel corso della discussione è stato affrontato un tema molto attuale, soprattutto per un Paese come l'Italia, dove il settore agroalimentare ha un valore non solo economico, ma anche culturale e identitario. Parlare di food italiano, infatti, non significa solo parlare di prodotti famosi nel mondo, ma anche di imprese, di organizzazione, di qualità, di sostenibilità e di tutte quelle scelte che stanno dietro a ciò che arriva ogni giorno sulle tavole.
      </p>
      <p>
        Uno degli aspetti più interessanti emersi durante l'incontro è stato proprio questo: dietro prodotti semplici e quotidiani come la pasta o l'olio c'è in realtà un sistema molto più complesso di quanto si possa pensare. Non si tratta solo di produzione o vendita, ma di rapporti tra aziende e agricoltori, controlli sulla qualità, gestione della filiera, investimenti e capacità di stare dentro un mercato sempre più globale. In questo senso, la parola "governance" assume un significato concreto, perché riguarda il modo in cui un'impresa sceglie di organizzarsi e di affrontare le difficoltà del presente.
      </p>
      <p>
        Sono intervenuti esperti di diritto e del settore per permetterci di ottenere una visione giuridica, ma allo stesso tempo pratica delle difficoltà normative e delle soluzioni adottate dalle aziende. La serata è stata moderata dal Prof. Giacomo Morri, ospitando l'Avv. Nicola Lucifero (LCA Studio Legale), l'Avv. Matilde Baratta (Mori Rossetti & Franzosi), il Dott. Marco De Matteis (De Matteis Agroalimentare S.p.A.) e il Dott. Sabino Basso (Olio Basso Fedele e Figli S.r.l.).
      </p>
      <h2>Il quadro normativo</h2>
      <p>
        Gli avvocati hanno avuto modo di illustrarci gli aspetti del nostro ordinamento giuridico riguardanti il settore agroalimentare, regolato da una legislazione non solo nazionale, ma anche regionale e perfino europea. Il mercato del food italiano è caratterizzato da una garanzia della sicurezza del prodotto, assicurato tramite vari aspetti fra cui il principio di rintracciabilità, i prodotti a zero rischio ecc. Difatti, secondo l'articolo 14 del regolamento 178/2002 gli alimenti dannosi per la salute oppure inadatti al consumo umano non possono essere immessi all'interno del mercato. Il regolamento stabilisce così i requisiti e i principi generali della legislazione alimentare europea.
      </p>
      <p>
        In più, le aziende italiane devono prestare attenzione nell'evitare di imbattersi in responsabilità penali che consistono in pene molto gravi. La discussione ha fatto rilievo sui danni che derivano dalla contraffazione dei prodotti alimentari e i possibili rimedi che possono essere adottati dalle stesse aziende. La contraffazione descrive una formazione illecita ex novo di un alimento che consiste in un danno diretto per l'imprenditore, causando perdita di fatturato, e soprattutto un danno di immagine che risulta da una perdita di attrattiva del marchio. Diverse sono state le soluzioni adottate per garantire la qualità del proprio prodotto, sia mediante un team di lavoro interno sia un organo esterno volto a svolgere determinati controlli. Fra i team di ricerca possiamo citare esperti di qualità e ricercatori che non solo si occupano di indagini interne e di attività di audit, ma che forniscono anche assistenza nell'ambito legale. Soprattutto, oggi sono diversi gli organi che coordinano attività di prevenzione e di repressione delle contraffazioni, come ad esempio la Cabina di Regia per i controlli amministrativi nel settore agroalimentare, un organo operativo presso il Ministero dell'Agricoltura, della Sovranità Alimentare e delle Foreste (MASAF). È un dipartimento del MASAF anche l'ispettorato centrale della tutela della qualità e repressione frodi, l'ICQRF, che opera come organo tecnico di polizia giudiziaria (PG). Dal 2021 fino al 2025, il numero complessivo dei controlli nel settore agroalimentare è cresciuto del 25,7%.
      </p>
      <h2>Il disegno di legge n. 1519/2026</h2>
      <p>
        Tra i provvedimenti di maggiore rilievo spicca, tra l'altro, il disegno di legge n. 1519/2026: <em>Disposizioni sanzionatorie a tutela dei prodotti alimentari italiani</em>, registrato come a.c. 2721. La finalità del provvedimento è quella di offrire una maggiore tutela in materia di reati agroalimentari, intervenendo su temi di tracciabilità del prodotto e sul sistema dei controlli. Il disegno di legge è stato approvato in prima lettura dal Senato e approvato definitivamente dalle Camere. È costituito da 21 articoli e suddiviso in tre sezioni: una sui rilievi penali, una su quelli amministrativi e l'ultima sulle disposizioni finali. Tra le modifiche apportate, vi è la riformulazione del Titolo VIII del Libro II del Codice Penale che è stato rinominato "Dei delitti contro l'economia pubblica, l'industria, il commercio e <strong>il patrimonio agroalimentare</strong>". Sono stati abrogati gli artt. 516 (che riguardava la vendita di sostanze alimentari non genuine come genuine) e 517-bis, il primo sostituito dal delitto di frode alimentare (<em>art. 517 - sexies</em>). È stato inserito così un nuovo Capo II-bis intitolato "Dei delitti contro il patrimonio agroalimentare", tra cui rientra <em>l'articolo 517-quater</em> che prevede un'estensione della punibilità alle condotte poste in essere tramite strumenti digitali e reti telematiche. È stato introdotto il delitto di commercio di alimenti con segni mendaci (<em>art. 517-septies c.p.</em>): la novità consiste nel far esplicitamente riferimento ad una frode posta a beni alimentari per indurre in errore il compratore – mentre il già esistente <em>art. 517 c.p.</em> parla esclusivamente di "opere dell'ingegno o prodotti industriali". In più rientra anche <em>l'art. 517 – novies</em> che illustra l'agropirateria.
      </p>
      <p>
        Il legislatore ha aggiunto, infine, una serie di pene accessorie applicabili in caso di condanna (ex. <em>art. 517 – octies</em> che consiste nella chiusura temporanea dello stabilimento nell'ambito del quale il fatto è stato commesso) e prevede la confisca obbligatoria delle cose destinate a commettere il reato.
      </p>
      <h2>La voce delle imprese: De Matteis Agroalimentare</h2>
      <p>
        Molto interessante è stato l'intervento del dott. Marco De Matteis, CEO di De Matteis Agroalimentare S.p.A., che ha mostrato il punto di vista dell'impresa in modo diretto e molto chiaro. Un passaggio importante ha riguardato il fatto che la pasta, pur essendo uno dei simboli più forti del Made in Italy, dipende da una materia prima, il grano duro, che rappresenta solo una piccola parte della produzione mondiale di cereali. Inoltre, l'Italia non è autosufficiente nella produzione di grano duro, quindi non riesce a coprire da sola tutto il proprio fabbisogno. Questo rende il settore esposto a molte variabili e dimostra quanto il tema della filiera sia centrale. L'esperienza dell'azienda De Matteis è sembrata particolarmente significativa proprio perché mostra come un'impresa possa cercare di rispondere a queste difficoltà con una visione più ampia. L'azienda, nata come realtà familiare, ha costruito negli anni una propria identità basata sul rapporto tra terra, persone e prodotto. Molto colpisce anche la scelta di essere diventata società benefit, inserendo tra i propri obiettivi non solo quelli economici, ma anche quelli legati alla tutela del territorio, alla crescita del personale, al riciclo, all'efficienza produttiva e alla riduzione dell'impatto ambientale. È un esempio concreto di come oggi fare impresa significhi anche assumersi una responsabilità più grande verso il contesto in cui si opera.
      </p>
      <p>
        Ancora più interessante è il progetto della <em>filiera Armando</em>, presentato come un modello costruito sulla collaborazione diretta tra azienda, agricoltori e centri di stoccaggio. L'idea di base è semplice ma molto forte: superare il rapporto di distanza o conflitto tra industria e agricoltura e creare invece un sistema fondato sulla fiducia e su obiettivi comuni. In questo caso, gli agricoltori seguono regole precise, vengono affiancati da agronomi e hanno anche una maggiore tutela grazie al prezzo minimo garantito. Questo modello fa capire bene che la qualità finale del prodotto non nasce per caso, ma è il risultato di un lavoro organizzato, controllato e condiviso.
      </p>
      <h2>Imprese familiari e passaggio generazionale</h2>
      <p>
        Anche l'intervento del dott. Sabino Basso ha offerto spunti importanti, soprattutto sul tema delle imprese familiari e del passaggio generazionale. Questo è un punto molto delicato per tante aziende italiane, perché spesso il problema non è solo conservare una tradizione, ma capire come portarla avanti senza restare fermi. L'idea che è emersa è che la nuova generazione non dovrebbe limitarsi a replicare il passato, ma dovrebbe cercare di migliorarlo, tenendo insieme eredità e cambiamento. È una riflessione molto attuale, soprattutto in un settore come quello agroalimentare, dove il legame con la storia conta tantissimo, ma da solo non basta più. Un altro punto interessante emerso dal suo intervento riguarda il fatto che l'Italia, pur essendo fortissima sul piano dell'immagine e del valore del Made in Italy, non è autosufficiente per molte materie prime agricole. Questo crea una specie di contraddizione: da una parte c'è un marchio conosciuto e apprezzato ovunque, dall'altra c'è la necessità di dipendere anche dall'esterno per sostenere la produzione. Proprio per questo, oggi la forza di un'impresa agroalimentare non si misura solo nella qualità del prodotto, ma anche nella capacità di organizzare bene la filiera, gestire le risorse e mantenere credibilità sul mercato.
      </p>
      <h2>Conclusioni</h2>
      <p>
        Nel complesso, la conferenza ha fatto emergere un'idea molto chiara: il futuro del food italiano dipende non solo dalla tradizione e dalla qualità, che restano fondamentali, ma anche dalla capacità delle imprese di adattarsi, innovare e costruire modelli più sostenibili. Il settore agroalimentare continua a essere uno dei punti di forza dell'Italia, ma oggi deve confrontarsi con problemi reali, come la scarsità delle materie prime, il cambiamento climatico, la competizione internazionale e la necessità di rendere più equilibrati i rapporti tra tutti i soggetti coinvolti nella produzione.
      </p>
      <p>
        In definitiva, la conferenza ha illustrato il complesso mondo agroalimentare all'interno del quale le aziende devono assicurare dei controlli mirati per sopravvivere ad un ordinamento giuridico aspro. L'incontro ha mostrato che il tema dell'agroalimentare va ben oltre il prodotto finale. Riguarda il modo in cui le imprese scelgono di stare sul mercato, di relazionarsi con il territorio e di costruire il proprio futuro. Ed è proprio da queste scelte che dipenderà, sempre di più, il futuro del food italiano.
      </p>
    </StellaPolareArticleLayout>
  );
}
