
INSERT INTO public.course_subjects (id, course, subject, cfu) VALUES
(351, 'BIG', 'Political Science and Comparative Politics', 8),
(352, 'BIG', 'Quantitative Methods for Social Sciences (Module I - Mathematics)', 6),
(353, 'BIG', 'Law (Module I - Comparative Public Law)', 6),
(354, 'BIG', 'Introduction to Economics (Module I - Microeconomics)', 8),
(355, 'BIG', 'Introduction to Economics (Module II - Macroeconomics)', 6),
(356, 'BIG', 'Political Philosophy', 6),
(357, 'BIG', 'Quantitative Methods for Social Sciences (Module II - Statistics)', 6),
(358, 'BIG', 'Marketing Research Skills for Public Policy', 3),
(359, 'BIG', 'Computer Science', 6),
(360, 'BIG', 'First Foreign Language', 5),
(361, 'BIG', 'Management of Government Organizations', 8),
(362, 'BIG', 'International Relations', 8),
(363, 'BIG', 'History (Module I - Global History)', 6),
(364, 'BIG', 'Public Economics', 8),
(365, 'BIG', 'Negotiation Skills', 3),
(366, 'BIG', 'Policy Evaluation', 8),
(367, 'BIG', 'Law (Module II - International and European Law)', 6),
(368, 'BIG', 'Economics and Politics of the European Union', 6),
(369, 'BIG', 'Political Economics', 8),
(370, 'BIG', 'Second Foreign Language', 5),
(371, 'BIG', 'Public Governance', 8),
(372, 'BIG', 'Sociology', 7),
(373, 'BIG', 'History (Module II - History of Political Institutions)', 6),
(374, 'BIG', 'Media, Political Elites and the Public', 6),
(375, 'BIG', 'Final Paper', 3);
